steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_IMAGE', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_IMAGE']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run','deploy','$_SERVICE',
        '--image','$_IMAGE',
        '--region','$_REGION',
        '--platform','managed',
        '--allow-unauthenticated'
      ]

substitutions:
  _SERVICE: all-in-one-fastapi-backend
  _REGION: asia-south2
  _IMAGE: asia-south2-docker.pkg.dev/all-in-one-fastapi-backend/cloud-run-source-deploy/all-in-one-fastapi-backend:$COMMIT_SHA
images:
  - '$_IMAGE'
